name: Analyse OWASP avec Semgrep

on:
  push:
    branches: [main]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer Semgrep (dernière version)
        run: |
          pip install --upgrade pip
          pip install semgrep

      - name: Analyse avec Semgrep (OWASP + verbose)
        run: |
          semgrep --config=p/owasp-top-ten --verbose --metrics=off
